### ISSUE TITLE
Filter Enhancement Requests

### ISSUE THREAD

**Issue by ToddBarkalowHPE** [grommet/grommet-index#76]
As discussed in Slack, we propose the following enhancements to Filters:
#1 Grommet Index Filter Calendar from/to

We have a requirement for selecting either a single date and/or time, or from date/time and to date/time.  An example is filtering activity alerts and tasks for a given date range.  This could be a drop-down calendar component.
#2 Grommet Index Filter reset ability

We have a requirement for resetting filter changes back to original state.
#3 Grommet Index Filter view choices

We have a requirement for allowing the user to select the view they desire, such as small tiles, large tiles, or list.
#4 Grommet Index Filter exact match typed value

**Comment by ericsoderberghp** [comment]
Rather than enhance grommet-index, we are moving towards adding smaller, focused components to grommet-addons. By doing this, callers can compose their own richer capabilities like the ones described here. We have converted grommet-ferret to use grommet-addons instead of grommet-index. You can see an example of a filter sidebar here: https://github.com/grommet/grommet-ferret/blob/master/src/js/components/activity/ActivityFilter.js

**Comment by ericsoderberghp** [comment]
Per prior comment, you can build a Sidebar to do these things and not use grommet-index for this.
